name: CI

on:
  push:
    branches: [ "main", "ci-testing" ]
  pull_request:
    branches: [ "main", "ci-testing" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run:  cargo build --release
      - name: Run tests
        run: cargo test --release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libconnector
          path: target/release/libconnector.so

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler -y
          rustup target add i686-linux-android
          rustup target add x86_64-linux-android
          rustup target add aarch64-linux-android
      - uses: actions/checkout@v3
      - name: Build
        run:  |
          cd libconnector-android
          export CARGO_TARGET_DIR="$PWD/build/cargo"
          (cd ../messages; cargo build -p messages --features protobuf)
          export PROTO_DIR=libconnector-android/src/main/assets/proto
          mkdir -p $PROTO_DIR
          mkdir -p ../libconnector-java/src/main/proto
          cp ../protocol/proto/{itd_ssdm_descriptions,cam*,cpm*,denm*,dsrc*,its*,mcm*,vam*,vru*}.proto $PROTO_DIR
          protoc $PROTO_DIR/*.proto --proto_path=$PROTO_DIR --java_out=../libconnector-java/src/main/proto
          ls -lah $PROTO_DIR
          ls -lah ../libconnector-java/src/main/proto
          (cd ..; cargo clean)
          ./gradlew assembleRelease --info
          cp libconnector-android/build/outputs/aar/*.aar .
          mkdir test && cd test && unzip ../libconnector-android-release.aar
          file jni/arm64-v8a/libconnector_jni.so
          file jni/x86/libconnector_jni.so
          file jni/x86_64/libconnector_jni.so
          ls -lah jni/*
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libconnector-android
          path: libconnector-android/libconnector-android-release.aar
  
